# Generated by Django 5.2.10 on 2026-02-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('list_type', models.CharField(choices=[('A', 'A-List'), ('B', 'B-List')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=10)),
                ('position', models.CharField(default='Unknown', max_length=20)),
                ('bats', models.CharField(default='R', max_length=1)),
                ('score', models.FloatField(default=0.0)),
                ('opponent', models.CharField(default='Unknown', max_length=20)),
                ('probable_pitcher', models.CharField(default='TBD', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
