# Generated by Django 5.2.10 on 2026-04-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_prediction_stadium'),
        ('predictor', '0013_prediction_xba_alter_score_breakdown'),
    ]

    operations = [
    ]
